// Copyright 2011 David Galles, University of San Francisco. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without modification, are
// permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this list of
// conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice, this list
// of conditions and the following disclaimer in the documentation and/or other materials
// provided with the distribution.
//
// THIS SOFTWARE IS PROVIDED BY <COPYRIGHT HOLDER> ``AS IS'' AND ANY EXPRESS OR IMPLIED
// WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
// ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
// ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// The views and conclusions contained in the software and documentation are those of the
// authors and should not be interpreted as representing official policies, either expressed
// or implied, of the University of San Francisco

var AUX_ARRAY_WIDTH = 25;
var AUX_ARRAY_HEIGHT = 25;
var AUX_ARRAY_START_Y = 50;

var VISITED_START_X = 475;
var PARENT_START_X = 400;

var HIGHLIGHT_CIRCLE_COLOR = "#000000";
var BFS_TREE_COLOR = "#0000FF";
var BFS_QUEUE_HEAD_COLOR = "#0000FF";


var QUEUE_START_X = 30;
var QUEUE_START_Y = 50;
var QUEUE_SPACING = 30;


function CCC2013S4BFS(am)
{
	this.init(am);
	
}

CCC2013S4BFS.prototype = new Graph();
CCC2013S4BFS.prototype.constructor = CCC2013S4BFS;
CCC2013S4BFS.superclass = Graph.prototype;

CCC2013S4BFS.prototype.addControls =  function()
{		
	addLabelToAlgorithmBar("Start Vertex: ");
	this.startField = addControlToAlgorithmBar("Text", "");
	this.startField.onkeydown = this.returnSubmit(this.startField,  this.startCallback.bind(this), 2, true);
	this.startField.size = 2;
	
	addLabelToAlgorithmBar("End Vertex: ");
	this.endField = addControlToAlgorithmBar("Text", "");
	this.endField.onkeydown = this.returnSubmit(this.endField,  this.startCallback.bind(this), 2, true);
	this.endField.size = 2;
	
	this.startButton = addControlToAlgorithmBar("Button", "Run BFS");
	this.startButton.onclick = this.startCallback.bind(this);
	
	this.sample1Button = addControlToAlgorithmBar("Button", "Sample Input1");
	this.sample1Button.onclick = this.sample1Callback.bind(this);
	
	this.sample2Button = addControlToAlgorithmBar("Button", "Sample Input2");
	this.sample2Button.onclick = this.sample2Callback.bind(this);
	

	//CCC2013S4BFS.superclass.addControls.call(this);
	// 【修改】传入 false，不让父类创建 "Undirected Graph" 选项，强制锁定为 Directed
	CCC2013S4BFS.superclass.addControls.call(this, false);
}

CCC2013S4BFS.prototype.init = function(am, w, h)
{
	showEdgeCosts = false;
	//传入第4个参数true(有向), 第5个参数true(必须是DAG无环图)
	CCC2013S4BFS.superclass.init.call(this, am, w, h, true, true);
	
	// Clear the random graph generated by parent class
	this.animationManager.resetAll();
	
	// Load sample input 1 by default
	this.startField.value = "3";
	this.endField.value = "2";
	this.loadSample1();
}

// override directedGraphCallback，禁止改变方向
CCC2013S4BFS.prototype.directedGraphCallback = function(newDirected, event)
{
    // 强制锁定为有向图，什么都不做
    // 确保 radio button 视觉上也锁回 directed
    if (this.directedGraphButton)
    {
        this.directedGraphButton.checked = true;
    }
}

// override smallGraphCallback，切换后强制重设标志位
CCC2013S4BFS.prototype.smallGraphCallback = function(event)
{
    if (this.size != SMALL_SIZE)
    {
        this.directed = true;   // 锁死
        this.isDAG = true;      // 锁死
        this.animationManager.resetAll();
        this.setup_small();
    }
}

// override largeGraphCallback，同上
CCC2013S4BFS.prototype.largeGraphCallback = function(event)
{
    if (this.size != LARGE_SIZE)
    {
        this.directed = true;   // 锁死
        this.isDAG = true;      // 锁死
        this.animationManager.resetAll();
        this.setup_large();
    }
}

// override newGraphCallback，同上
CCC2013S4BFS.prototype.newGraphCallback = function(event)
{
    this.directed = true;   // 锁死
    this.isDAG = true;      // 锁死
    this.animationManager.resetAll();
    this.setup();
}


CCC2013S4BFS.prototype.setup = function() 
{
	CCC2013S4BFS.superclass.setup.call(this);
	this.messageID = new Array();
	this.commands = new Array();
	this.visitedID = new Array(this.size);
	this.visitedIndexID = new Array(this.size);
	this.parentID = new Array(this.size);
	this.parentIndexID = new Array(this.size);
	
	for (var i = 0; i < this.size; i++)
	{
		this.visitedID[i] = this.nextIndex++;
		this.visitedIndexID[i] = this.nextIndex++;
		this.parentID[i] = this.nextIndex++;
		this.parentIndexID[i] = this.nextIndex++;
		this.cmd("CreateRectangle", this.visitedID[i], "f", AUX_ARRAY_WIDTH, AUX_ARRAY_HEIGHT, VISITED_START_X, AUX_ARRAY_START_Y + i*AUX_ARRAY_HEIGHT);
		this.cmd("CreateLabel", this.visitedIndexID[i], i, VISITED_START_X - AUX_ARRAY_WIDTH , AUX_ARRAY_START_Y + i*AUX_ARRAY_HEIGHT);
		this.cmd("SetForegroundColor",  this.visitedIndexID[i], VERTEX_INDEX_COLOR);
		this.cmd("CreateRectangle", this.parentID[i], "", AUX_ARRAY_WIDTH, AUX_ARRAY_HEIGHT, PARENT_START_X, AUX_ARRAY_START_Y + i*AUX_ARRAY_HEIGHT);
		this.cmd("CreateLabel", this.parentIndexID[i], i, PARENT_START_X - AUX_ARRAY_WIDTH , AUX_ARRAY_START_Y + i*AUX_ARRAY_HEIGHT);
		this.cmd("SetForegroundColor",  this.parentIndexID[i], VERTEX_INDEX_COLOR);
		
	}
	this.cmd("CreateLabel", this.nextIndex++, "Parent", PARENT_START_X - AUX_ARRAY_WIDTH, AUX_ARRAY_START_Y - AUX_ARRAY_HEIGHT * 1.5, 0);
	this.cmd("CreateLabel", this.nextIndex++, "Visited", VISITED_START_X - AUX_ARRAY_WIDTH, AUX_ARRAY_START_Y - AUX_ARRAY_HEIGHT * 1.5, 0);
	this.cmd("CreateLabel", this.nextIndex++, "BFS Queue", QUEUE_START_X, QUEUE_START_Y - 30, 0);
	animationManager.setAllLayers([0, this.currentLayer]);
	animationManager.StartNewAnimation(this.commands);
	animationManager.skipForward();
	animationManager.clearHistory();
	this.highlightCircleL = this.nextIndex++;
	this.highlightCircleAL = this.nextIndex++;
	this.highlightCircleAM= this.nextIndex++
}

CCC2013S4BFS.prototype.setupCustomGraph = function()
{
	this.commands = new Array();
	this.circleID = new Array(this.size);
	
	// Use large graph settings for 10 vertices
	this.allowed = LARGE_ALLOWED;
	this.curve = LARGE_CURVE;
	this.x_pos_logical = LARGE_X_POS_LOGICAL;
	this.y_pos_logical = LARGE_Y_POS_LOGICAL;
	this.adj_matrix_x_start = LARGE_ADJ_MATRIX_X_START;
	this.adj_matrix_y_start = LARGE_ADJ_MATRIX_Y_START;
	this.adj_matrix_width = LARGE_ADJ_MATRIX_WIDTH;
	this.adj_matrix_height = LARGE_ADJ_MATRIX_HEIGHT;
	this.adj_list_x_start = LARGE_ADJ_LIST_X_START;
	this.adj_list_y_start = LARGE_ADJ_LIST_Y_START;
	this.adj_list_elem_width = LARGE_ADJ_LIST_ELEM_WIDTH;
	this.adj_list_elem_height = LARGE_ADJ_LIST_ELEM_HEIGHT;
	this.adj_list_height = LARGE_ADJ_LIST_HEIGHT;
	this.adj_list_width = LARGE_ADJ_LIST_WIDTH;
	this.adj_list_spacing = LARGE_ADJ_LIST_SPACING;
	
	// Create circles for vertices
	for (var i = 0; i < this.size; i++)
	{
		this.circleID[i] = this.nextIndex++;
		this.cmd("CreateCircle", this.circleID[i], i, this.x_pos_logical[i], this.y_pos_logical[i]);
		this.cmd("SetTextColor", this.circleID[i], VERTEX_INDEX_COLOR, 0);
		this.cmd("SetLayer", this.circleID[i], 1);
	}
	
	// Initialize adj_matrixID array
	this.adj_matrixID = new Array(this.size);
	for (var i = 0; i < this.size; i++)
	{
		this.adj_matrixID[i] = new Array(this.size);
	}
	
	// Build edges from custom adjacency matrix
	this.buildEdges();
	
	// Build adjacency list
	this.buildAdjList();
	
	// Build adjacency matrix
	this.buildAdjMatrix();
	
	// Set up BFS arrays
	this.messageID = new Array();
	this.visitedID = new Array(this.size);
	this.visitedIndexID = new Array(this.size);
	this.parentID = new Array(this.size);
	this.parentIndexID = new Array(this.size);
	
	for (var i = 0; i < this.size; i++)
	{
		this.visitedID[i] = this.nextIndex++;
		this.visitedIndexID[i] = this.nextIndex++;
		this.parentID[i] = this.nextIndex++;
		this.parentIndexID[i] = this.nextIndex++;
		this.cmd("CreateRectangle", this.visitedID[i], "f", AUX_ARRAY_WIDTH, AUX_ARRAY_HEIGHT, VISITED_START_X, AUX_ARRAY_START_Y + i*AUX_ARRAY_HEIGHT);
		this.cmd("CreateLabel", this.visitedIndexID[i], i, VISITED_START_X - AUX_ARRAY_WIDTH , AUX_ARRAY_START_Y + i*AUX_ARRAY_HEIGHT);
		this.cmd("SetForegroundColor",  this.visitedIndexID[i], VERTEX_INDEX_COLOR);
		this.cmd("CreateRectangle", this.parentID[i], "", AUX_ARRAY_WIDTH, AUX_ARRAY_HEIGHT, PARENT_START_X, AUX_ARRAY_START_Y + i*AUX_ARRAY_HEIGHT);
		this.cmd("CreateLabel", this.parentIndexID[i], i, PARENT_START_X - AUX_ARRAY_WIDTH , AUX_ARRAY_START_Y + i*AUX_ARRAY_HEIGHT);
		this.cmd("SetForegroundColor",  this.parentIndexID[i], VERTEX_INDEX_COLOR);
	}
	
	this.cmd("CreateLabel", this.nextIndex++, "Parent", PARENT_START_X - AUX_ARRAY_WIDTH, AUX_ARRAY_START_Y - AUX_ARRAY_HEIGHT * 1.5, 0);
	this.cmd("CreateLabel", this.nextIndex++, "Visited", VISITED_START_X - AUX_ARRAY_WIDTH, AUX_ARRAY_START_Y - AUX_ARRAY_HEIGHT * 1.5, 0);
	this.cmd("CreateLabel", this.nextIndex++, "BFS Queue", QUEUE_START_X, QUEUE_START_Y - 30, 0);
	
	animationManager.setAllLayers([0, this.currentLayer]);
	animationManager.StartNewAnimation(this.commands);
	animationManager.skipForward();
	animationManager.clearHistory();
	this.highlightCircleL = this.nextIndex++;
	this.highlightCircleAL = this.nextIndex++;
	this.highlightCircleAM= this.nextIndex++
}

CCC2013S4BFS.prototype.sample1Callback = function(event)
{
	this.animationManager.resetAll();
	this.startField.value = "3";
	this.endField.value = "2";
	this.loadSample1();
}

CCC2013S4BFS.prototype.sample2Callback = function(event)
{
	this.animationManager.resetAll();
	this.startField.value = "3";
	this.endField.value = "2";
	this.loadSample2();
}

CCC2013S4BFS.prototype.loadSample1 = function()
{
	this.commands = new Array();
	this.size = 10;
	
	// Initialize adjacency matrix with -1 (no edge)
	this.adj_matrix = new Array(this.size);
	for (var i = 0; i < this.size; i++)
	{
		this.adj_matrix[i] = new Array(this.size);
		for (var j = 0; j < this.size; j++)
		{
			this.adj_matrix[i][j] = -1;
		}
	}
	// Sample Input 1: 8 4, 3 8, 4 2
	this.adj_matrix[8][4] = 1;
	this.adj_matrix[3][8] = 1;
	this.adj_matrix[4][2] = 1;
	
	this.implementAction(this.setupCustomGraph.bind(this), "");
}

CCC2013S4BFS.prototype.loadSample2 = function()
{
	this.commands = new Array();
	this.size = 10;
	
	// Initialize adjacency matrix with -1 (no edge)
	this.adj_matrix = new Array(this.size);
	for (var i = 0; i < this.size; i++)
	{
		this.adj_matrix[i] = new Array(this.size);
		for (var j = 0; j < this.size; j++)
		{
			this.adj_matrix[i][j] = -1;
		}
	}
	// Sample Input 2: 3 8, 2 8, 3 4
	this.adj_matrix[3][8] = 1;
	this.adj_matrix[2][8] = 1;
	this.adj_matrix[3][4] = 1;
	
	this.implementAction(this.setupCustomGraph.bind(this), "");
}

CCC2013S4BFS.prototype.startCallback = function(event)
{
	var startValue;
	var endValue;
	
	if (this.startField.value != "" && this.endField.value != "")
	{
		startValue = this.startField.value;
		endValue = this.endField.value;

		var startVertex = parseInt(startValue);
		var endVertex = parseInt(endValue);

		// 限制一下范围，防止数组越界
		//this.implementAction 的签名通常只接受两个参数：第一个是绑定的函数，第二个是传给该函数的一个字符串参数
		//最稳妥、改动最小的做法就是将起点和终点用逗号（或其他分隔符）拼成一个字符串传过去, 然后在 doBFS 内部再将其切开
		if (startVertex >= 0 && startVertex < this.size && endVertex >= 0 && endVertex < this.size) {
			var combinedArgs = startValue + "," + endValue;
			this.implementAction(this.doBFS.bind(this), combinedArgs);
		}
	}
}



CCC2013S4BFS.prototype.doBFS = function(combinedArgs)
{
	var args = combinedArgs.split(",");
    var startVertex = args[0];
    var endVertex = args[1];
	this.visited = new Array(this.size);
	this.commands = new Array();
	this.queue = new Array(this.size);
	var head = 0;
	var tail = 0;
	var queueID = new Array(this.size);
	var queueSize = 0;
	
	if (this.messageID != null)
	{
		for (var i = 0; i < this.messageID.length; i++)
		{
			this.cmd("Delete", this.messageID[i]);
		}
	}
	
	this.rebuildEdges();
	this.messageID = new Array();
	for (i = 0; i < this.size; i++)
	{
		this.cmd("SetText", this.visitedID[i], "f");
		this.cmd("SetText", this.parentID[i], "");
		this.visited[i] = false;
		queueID[i] = this.nextIndex++;
		
	}
	var vertex = parseInt(startVertex);
	var target = parseInt(endVertex);
	this.visited[vertex] = true;
	this.queue[tail] = vertex;			
	this.cmd("CreateLabel", queueID[tail],  vertex, QUEUE_START_X + queueSize * QUEUE_SPACING, QUEUE_START_Y);
	queueSize = queueSize + 1;
	tail = (tail + 1) % (this.size);
	
	var found = false;
	
	while (queueSize > 0 && !found)
	{
		vertex = this.queue[head];
		this.cmd("CreateHighlightCircle", this.highlightCircleL, HIGHLIGHT_CIRCLE_COLOR, this.x_pos_logical[vertex], this.y_pos_logical[vertex]);
		this.cmd("SetLayer", this.highlightCircleL, 1);
		this.cmd("CreateHighlightCircle", this.highlightCircleAL, HIGHLIGHT_CIRCLE_COLOR,this.adj_list_x_start - this.adj_list_width, this.adj_list_y_start + vertex*this.adj_list_height);
		this.cmd("SetLayer", this.highlightCircleAL, 2);
		this.cmd("CreateHighlightCircle", this.highlightCircleAM, HIGHLIGHT_CIRCLE_COLOR,this.adj_matrix_x_start  - this.adj_matrix_width, this.adj_matrix_y_start + vertex*this.adj_matrix_height);
		this.cmd("SetLayer", this.highlightCircleAM, 3);
		
		this.cmd("SetTextColor", queueID[head], BFS_QUEUE_HEAD_COLOR);
		
		
		for (var neighbor = 0; neighbor < this.size; neighbor++)
		{
			if (this.adj_matrix[vertex][neighbor] > 0)
			{
				this.highlightEdge(vertex, neighbor, 1);
				this.cmd("SetHighlight", this.visitedID[neighbor], 1);
				this.cmd("Step");
				if (!this.visited[neighbor])
				{
					this.visited[neighbor] = true;
					this.cmd("SetText", this.visitedID[neighbor], "T");
					this.cmd("SetText", this.parentID[neighbor], vertex);
					this.highlightEdge(vertex, neighbor, 0);
					this.cmd("Disconnect", this.circleID[vertex], this.circleID[neighbor]);
					this.cmd("Connect", this.circleID[vertex], this.circleID[neighbor], BFS_TREE_COLOR, this.curve[vertex][neighbor], 1, "");
					this.queue[tail] = neighbor;
					this.cmd("CreateLabel", queueID[tail],  neighbor, QUEUE_START_X + queueSize * QUEUE_SPACING, QUEUE_START_Y);
					tail = (tail + 1) % (this.size);
					queueSize = queueSize + 1;
					
					if (neighbor == target)
					{
						found = true;
						break;
					}
				}
				else
				{
					this.highlightEdge(vertex, neighbor, 0);
				}
				this.cmd("SetHighlight", this.visitedID[neighbor], 0);
				this.cmd("Step");						
			}
			
		}
		this.cmd("Step");
		
		this.cmd("Delete", queueID[head]);
		head = (head + 1) % (this.size);
		queueSize = queueSize - 1;
		for (i = 0; i < queueSize; i++)
		{
			var nextQueueIndex = (i + head) % this.size;
			this.cmd("Move", queueID[nextQueueIndex], QUEUE_START_X + i * QUEUE_SPACING, QUEUE_START_Y);
		}
		this.cmd("Step");
		this.cmd("Step");
		
		this.cmd("Delete", this.highlightCircleL);
		this.cmd("Delete", this.highlightCircleAM);
		this.cmd("Delete", this.highlightCircleAL);
		
	}
	
	if (found)
	{
		this.cmd("CreateLabel", this.nextIndex++, "Found", 500, 400, 0);
	}
	else
	{
		this.cmd("CreateLabel", this.nextIndex++, "Not Found", 500, 400, 0);
	}
	
	return this.commands

}



CCC2013S4BFS.prototype.reset = function()
{
	
}



CCC2013S4BFS.prototype.enableUI = function(event)
{			
	this.startField.disabled = false;
	this.endField.disabled = false;
	this.startButton.disabled = false;
	this.sample1Button.disabled = false;
	this.sample2Button.disabled = false;
	
	
	CCC2013S4BFS.superclass.enableUI.call(this,event);
}

CCC2013S4BFS.prototype.disableUI = function(event)
{
	
	this.startField.disabled = true;
	this.endField.disabled = true;
	this.startButton.disabled = true;
	this.sample1Button.disabled = true;
	this.sample2Button.disabled = true;
	
	CCC2013S4BFS.superclass.disableUI.call(this, event);
}


var currentAlg;

function init()
{
	var animManag = initCanvas();
	currentAlg = new CCC2013S4BFS(animManag, canvas.width, canvas.height);
}
